ExamsProjectMvc/Models/TeachersModels/CreateExamViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Common;

namespace ExamsProjectMvc.Models.TeachersModels
{
    public class CreateExamViewModel : ExamViewModel, IExamBase
    {
        public int ExamID { get; set; }
        public IEnumerable<IClassroom> Classrooms { get; set; }

        public int ClassroomID { get; set; }

        public string MinDate { get; set; }
        public string MaxDate { get; set; }

        IEnumerable<IQuestion> IExamBase.Questions
        {
            get { return Questions; }
            set { Questions = value as IEnumerable<QuestionViewModel>; }
        }
    }
}

ExamsProjectMvc/Models/TeachersModels/QuestionViewModel.cs
using Common; 
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamsProjectMvc.Models.TeachersModels
{
    public class QuestionViewModel : IQuestion
    {
        public int QuestionID { get; set; }
        public string QuestionText { get; set; }
        public int ExamID { get; set; }
        [JsonIgnore]
        public IExam Exam { get; set; }
        public IEnumerable<AnswerChoiceViewModel> AnswerChoises { get; set; }
        IEnumerable<IAnswerChoise> IQuestion.AnswerChoises
        {
            get { return AnswerChoises; }
            set { AnswerChoises = value as IEnumerable<AnswerChoiceViewModel>; }
        }
        public string CorrectAnswerText { get; set; }
    }
}

ExamsProjectMvc/Controllers/TeachersController.cs
using Common;
using DAL;
using DAL.Models;
using ExamsProjectMvc.Models;
using ExamsProjectMvc.Models.TeachersModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace ExamsProjectMvc.Controllers
{
    public class TeachersController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public TeachersController(ILogger<HomeController> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            string teacherId = HttpContext.Request.Cookies["userId"];
            if (teacherId != null)
            {
                ITeacher teacher = _unitOfWork.GetTeacherById(int.Parse(teacherId));
                if (teacher != null)
                {
                    TeacherIndexViewModel vm = ViewModelsFactory.CreateTeacherIndexViewModel(teacher);
                    // ViewData["loged"] = "true";

                    return View(vm);
                }
                Response.Cookies.Delete("userId");
            }
            return RedirectToAction("Login");

        }

        [HttpGet]
        public IActionResult Login()
        {
            string teacherId = HttpContext.Request.Cookies["userId"];
            if (teacherId != null)
            {
                return RedirectToAction("Index");
            }
            return View("TeachersLogin", new LoginViewModel());
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel vm)
        {
            if (ModelState.IsValid)
            {
                int studentid = _unitOfWork.GetTeacherId(vm.LoginName, vm.Password);
                if (studentid != 0)
                {
                    CookieOptions options = new CookieOptions();
                    if (vm.StayConnected)
                    {
                        options.Expires = DateTime.Now.AddDays(7);
                    }
                    HttpContext.Response.Cookies.Append("userId", studentid.ToString(), options);
                    HttpContext.Response.Cookies.Append("userType", Enums.UserType.Teacher.ToString(), options);
                    HttpContext.Response.Cookies.Append("isLoged", "true", options);


                    return RedirectToAction("Index");
                }
                vm.IsAttempFailed = true;
                ViewData["errorMessage"] = "Incorrect Login Name or Password";
            }
            return View("TeachersLogin", vm);
        }
        public IActionResult Logout()
        {
            return RedirectToAction("Logout", "Home");
        }

        public IActionResult CreateExam()
        {
            string teacherId = HttpContext.Request.Cookies["userId"];
            if (teacherId != null)
            {
                ITeacher teacher = _unitOfWork.GetTeacherById(int.Parse(teacherId));
                if (teacher != null)
                {
                    CreateExamViewModel vm = ViewModelsFactory.CreateCreateExamViewModel(teacher);
                    return View(vm);
                }
            }
            return RedirectToAction("Login");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateExam(CreateExamViewModel vm)
        {
            if (ModelState.IsValid)
            {
                foreach (var question in vm.Questions)
                {
                    foreach (var answer in question.AnswerChoises)
                    {
                        if (answer.AnswerChoiceText == question.CorrectAnswerText)
                        {
                            answer.IsCorrectAnswer = true;
                        }
                    }
                }
                try
                {
                    int examId = _unitOfWork.AddExam(vm);
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    return NotFound();
                }
            }
            return View(vm);
        }

        [HttpGet]
        public IActionResult EditExam(int id)
        {
            string teacherId = HttpContext.Request.Cookies["userId"];
            if (teacherId != null)
            {
                ITeacher teacher = _unitOfWork.GetTeacherById(int.Parse(teacherId));
                if (teacher != null)
                {
                    try
                    {

                        IExam examToEdit = _unitOfWork.GetExamById(id);
                        if (examToEdit != null)
                        {
                            if (examToEdit.TeacherID == teacher.ID)
                            {
                                CreateExamViewModel vm = ViewModelsFactory.CreateCreateExamViewModel(teacher, examToEdit);
                                var questionsJson = JsonConvert.SerializeObject(vm.Questions);
                                ViewData["ExamQuestions"] = questionsJson;
                                return View(vm);
                            }
                        }
                        return NotFound();
                    }
                    catch (Exception e)
                    {
                        return NotFound();
                    }
                }
            }
            return RedirectToAction("Login");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditExam(CreateExamViewModel vm)
        {
            if (ModelState.IsValid)
            {
                foreach (var question in vm.Questions)
                {
                    foreach (var answer in question.AnswerChoises)
                    {
                        if (answer.AnswerChoiceText == question.CorrectAnswerText)
                        {
                            answer.IsCorrectAnswer = true;
                        }
                    }
                }
                try
                {
                    int examId = _unitOfWork.EditExam(vm);
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    return NotFound();
                }
            }
            return View(vm);
        }

        public IActionResult ExamStatistics(int id)
        {
            string teacherId = HttpContext.Request.Cookies["userId"];
            if (teacherId != null)
            {
                IExam exam = _unitOfWork.GetExamById(id);
                if (exam != null)
                {
                    DateTime examEndTime = exam.StartTime.AddMinutes(exam.ExamDurationInMinutes);
                    if (exam.TeacherID == int.Parse(teacherId) && examEndTime < DateTime.Now)
                    {
                        ExamStatsViewModel vm = ViewModelsFactory.CreateExamStatsViewModel(exam);
                        return View("ExamStatistics", vm);

                    }
                    return RedirectToAction("Index"); //If exam still in progress show index
                }
                return NotFound(); //Show some alert
            }
            return RedirectToAction("Login");
        }

        public IActionResult ReviewExam(int id, int studentId)
        {
            string teacherId = HttpContext.Request.Cookies["userId"];
            if (teacherId != null)
            {
                try
                {
                    IStudent_Exam se = _unitOfWork.GetStudentExam(id, studentId);
                    if (se != null && se.Exam.TeacherID == int.Parse(teacherId))
                    {
                        return View(se);
                    }
                    return NotFound();
                }
                catch (Exception e)
                {
                    return NotFound();
                }
            }
            return RedirectToAction("Login");
        }

        public ActionResult DeleteExam(int id)
        {
            string teacherId = HttpContext.Request.Cookies["userId"];
            if (teacherId != null)
            {
                IExam examToDelete = _unitOfWork.GetExamById(id);
                if (examToDelete != null)
                {
                    if (examToDelete.TeacherID == int.Parse(teacherId))
                    {
                        ExamViewModel vm = ViewModelsFactory.CreateExamViewMode(examToDelete);
                        return View(vm);
                    }
                }
                return NotFound();
            }
            return RedirectToAction("Login");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteExam(int ExamId, int TeacherID, object exam)
        {
            string teacherId = HttpContext.Request.Cookies["userId"];
            if (teacherId != null)
            {
                try
                {
                    if (TeacherID == int.Parse(teacherId))
                    {
                        _unitOfWork.DeleteExam(ExamId);
                        return RedirectToAction(nameof(Index));
                    }
                    return NotFound();
                }
                catch (Exception e)
                {
                    return View();
                }
            }
            return RedirectToAction("Login");
        }

        public IActionResult Details(int id)
        {
            {
                string teacherId = HttpContext.Request.Cookies["userId"];
                if (teacherId != null)
                {
                    try
                    {
                        IExam exam = _unitOfWork.GetExamById(id);
                        if (exam != null)
                        {

ExamsProjectMvc/Views/Teachers/CreateExam.cshtml
@model ExamsProjectMvc.Models.TeachersModels.CreateExamViewModel

@{
    ViewData["Title"] = "CreateExam";
    Layout = "~/Views/Teachers/_TeachersLayoutPage.cshtml";
    ViewData["SbumitText"] = "Create Exam";
}


<hr />
<div class="row">
    <div class="col">
        <form asp-action="CreateExam" onsubmit="return checkForm(event)">
            <partial name="CreateExamForm" />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to homepage</a>
</div>

@section Scripts{

    <script src="~/js/createexam.js"></script>
    <script src="~/js/checkexamform.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            createNewQuestionCard(true);

        });
    </script>
}

ExamsProjectMvc/Views/Teachers/CreateExamForm.cshtml
@model ExamsProjectMvc.Models.TeachersModels.CreateExamViewModel
@using System.Globalization;
@{
    string submitButtonValue = ViewData["SbumitText"].ToString();
    string examDate;
    examDate = Model.StartTime.ToString("s", CultureInfo.CreateSpecificCulture("fr-FR"));
    examDate = examDate.Remove(examDate.Length - 3);
}


<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div id="hidden">
    <input asp-for="TeacherID" type="hidden" />
    <input asp-for="ClassroomID" type="hidden" />
    <input asp-for="ExamID" type="hidden" />
</div>
<div class="row">
    <div class="col">

        <div class="card text-white bg-dark ">
            <div class="card-header">
                <div class="form-group">
                    <input asp-for="Title" id="title" class="form-control form-control-lg" placeholder="Enter Exam Title" style="height:80px; font-size:60px" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

            </div>
            <div class="card-body">
                <div class="form-group">
                    <textarea asp-for="Description" id="description" class="form-control" placeholder="Enter Description" rows="3"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-row">
                    <div class="col">

                        <div class="form-group">
                            <label asp-for="StartTime" class="control-label"></label>
                            <input asp-for="StartTime" id="startTime" class="form-control" max="@Model.MaxDate" min="@Model.MinDate" value="@examDate" />
                            <span asp-validation-for="StartTime" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col">

                        <div class="form-group">
                            <label asp-for="ExamDurationInMinutes" class="control-label"></label>
                            <input asp-for="ExamDurationInMinutes" class="form-control" step="10" min="0" />
                            <span asp-validation-for="ExamDurationInMinutes" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col">

                        <div class="form-group">
                            <label for="classroomSelect">Assign to classroom</label>
                            <select class="form-control" id="classroomSelect">
                                @foreach (var item in Model.Classrooms)
                                {
                                    if (Model.ClassroomID == item.ClassroomID)
                                    {
                                        <option value="@item.ClassroomID" selected="selected">@item.Title</option>
                                    }
                                    else
                                    {
                                        <option value="@item.ClassroomID">@item.Title</option>
                                    }
                                }

                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<partial name="questionForm" />
<hr />
<div class="row">
    <div class="col text-right">
        <div class="form-group">
            <input type="submit" value="@submitButtonValue" class="btn btn-success" />
        </div>
    </div>
</div>

ExamsProjectMvc/Views/Teachers/DeleteExam.cshtml
@model ExamsProjectMvc.Models.TeachersModels.ExamViewModel

@{
    ViewData["Title"] = "EditExam";
    Layout = "~/Views/Teachers/_TeachersLayoutPage.cshtml";
}


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Model.Title</h4>
    <hr />
    <partial name="_BasicExamDetails" model="@Model" />
    <partial name="questionsDetails" model="@Model.Questions" />

    <form asp-action="DeleteExam">
        <input type="hidden" asp-for="ExamID" />
        <input type="hidden" asp-for="TeacherID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to Index</a>
    </form>
</div>

ExamsProjectMvc/Views/Teachers/EditExam.cshtml
@model ExamsProjectMvc.Models.TeachersModels.CreateExamViewModel
@using ExamsProjectMvc.Models.TeachersModels
@using Newtonsoft.Json;
@{

    ViewData["Title"] = "EditExam";
    Layout = "~/Views/Teachers/_TeachersLayoutPage.cshtml";
    ViewData["SbumitText"] = "Edit Exam";
    string questionsJson = ViewData["ExamQuestions"].ToString();
}


<hr />
<div class="row">
    <div class="col">
        <form asp-action="EditExam" onsubmit="return checkForm(event)">
            
            <partial name="CreateExamForm" />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to homepage</a>
</div>

@section Scripts{

    <script src="~/js/createexam.js"></script>
    <script src="~/js/checkexamform.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            let questionsData = @Html.Raw(questionsJson);
            console.log(questionsData);
           // let questionsData = JSON.parse(jsonData);
            if (questionsData !== null) {
                if (questionsData.constructor === Array) {
                    let firstQuestion = true;
                    questionsData.forEach((question, index) => {
                        if (firstQuestion) {
                            createNewQuestionCard(true);
                            firstQuestion = false;
                        }
                        else {
                            addQuestion();
                        }
                        fillQuestionCard(question, index+1);
                    });
                }
            }
        });

        function fillQuestionCard(question, index) {
            let cardDiv = document.getElementById(`questionCard${index}`);
            let cardBody = cardDiv.querySelector(".card-body");
            let questionTextInput = cardDiv.querySelector("#questionInputText");
            questionTextInput.value = question.QuestionText;

            question.AnswerChoises.forEach((answer, answerIndex) => {
                    let textInput = cardDiv.querySelector(`#optionText${answerIndex + 1}`);
                    textInput.value = answer.AnswerChoiceText;
                if (answerIndex >= 1) {
                    textInput.focus();
                    textInput.blur();
                }
                if (answer.IsCorrectAnswer) {
                    //Set the radio
                    let radioElement = cardDiv.querySelector(`#option${answerIndex + 1}`);
                    radioElement.checked = true;
                }
            })

        }

    </script>
}

ExamsProjectMvc/Views/Teachers/ExamDetails.cshtml
@model ExamsProjectMvc.Models.TeachersModels.ExamViewModel

@{
    ViewData["Title"] = "Exam Details";
    Layout = "~/Views/Teachers/_TeachersLayoutPage.cshtml";
}


<h3>Exam Details</h3>
<div>
    <h4>@Model.Title</h4>
    <hr />
    <partial name="_BasicExamDetails" model="@Model" />
    <partial name="questionsDetails" model="@Model.Questions" />
    <a asp-action="Index">Back to Index</a>
</div>

ExamsProjectMvc/Views/Teachers/Index.cshtml
@model ExamsProjectMvc.Models.TeachersModels.TeacherIndexViewModel
@{
    ViewData["Title"] = "Home";
    Layout = "_TeachersLayoutPage.cshtml";
}

<div class="jumbotron alert-primary">
    <div class="row">
        <div class="col">
            <h1>Hello, @Model.Name!</h1>

            <h3>Welcome to your personal space!</h3>
            <p>Here you can create exams and review past exams.</p>
        </div>
    </div>
</div>
@if (Model.Classrooms.Count > 0)
{
    <div class="row" id="classrooms">
        <div class="col">
            <h2>Classrooms</h2>

            <div class="alert alert-dismissible alert-secondary">
                <h4>The classrooms you are assigned to are:</h4>
                <ul class="list-group">
                    @foreach (var classroom in Model.Classrooms)
                    {
                        <li class="list-group-item d-flex justify-content-between align-items-center">@Html.DisplayFor(classroomModel => classroom.Title)</li>
                    }
                </ul>
            </div>
        </div>
    </div>
}
<div class="row" id="createExams">
    <div class="col">
        <h2>Create Exam</h2>
        <div class="alert alert-dismissible alert-secondary">
            <h4>Click below to create a new exam</h4>
            <a asp-controller="Teachers" asp-action="CreateExam">
                <input type="button" class="btn btn-lg btn-primary" value="Create New Exam" />
            </a>
        </div>
    </div>
</div>
<div class="row" id="todayExams">
    <div class="col">
        <h2>Exams For Today</h2>
        @if (Model.TodayExams.Count > 0)
        {
            <div class="card">
                <table class="table table-hover">
                    <thead>
                        <tr class="table-secondary">
                            <th>
                                Exam Title
                            </th>
                            <th>
                                Classroom Title
                            </th>
                            <th>
                                Date
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.TodayExams)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Classroom.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StartTime)
                                </td>
                                <td>
                                    <a asp-action="Details" asp-route-id="@item.ExamID">
                                        <input type="button" class="btn btn-primary" value="View Exam" />
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <div class="alert alert-success">
                <h4>No exams to show</h4>
                <p>There are no exams today.</p>
            </div>
        }
    </div>
</div>
<hr />
<div class="row" id="futureExams">
    <div class="col">
        <h2>Future Exams</h2>
        @if (Model.FutureExams.Count > 0)
        {
            <div class="card">
                <table class="table table-hover">
                    <thead>
                        <tr class="table-secondary">
                            <th>
                                Exam Title
                            </th>
                            <th>
                                Classroom Title
                            </th>
                            <th>
                                Date
                            </th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.FutureExams)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Classroom.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StartTime)
                                </td>
                                <td>
                                    <a asp-action="EditExam" asp-route-id="@item.ExamID">
                                        <input type="button" class="btn btn-primary" value="Edit" />
                                    </a>
                                </td>
                                <td>
                                    <a asp-action="DeleteExam" asp-route-id="@item.ExamID">
                                        <input type="button" class="btn btn-danger" value="Delete" />
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <div class="alert alert-dismissible alert-secondary">
                <h4>No exams to show</h4>
                <p>Looks like you don't have any exams coming up.</p>
            </div>
        }
    </div>
</div>
<hr />
<div class="row" id="pastExams">
    <div class="col">
        <h2>Past Exams</h2>
        @if (Model.PastExams.Count > 0)
        {
            <div class="card">
                <table class="table table-hover">
                    <thead>
                        <tr class="table-secondary">
                            <th>
                                Exam Title
                            </th>
                            <th>
                                Classroom Title
                            </th>
                            <th>
                                Date
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.PastExams)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Classroom.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StartTime)
                                </td>
                                <td>
                                    <a asp-action="ExamStatistics" asp-route-id="@item.ExamID">
                                        <input type="button" class="btn btn-info" value="Review Exam" />
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <div class="alert alert-dismissible alert-secondary">
                <h4>No exams to show</h4>
                <p>Looks like didn't have any tests yet</p>
            </div>
        }
    </div>
</div>

@section Scripts
{
    <script>
        function directToExamStatistics(id) {
            window.location.href = `/Teachers/ExamStatistics/${id}`;
        }
    </script>
}

ExamsProjectMvc/Views/Teachers/ReviewExam.cshtml
@model Common.IStudent_Exam

@{
    ViewData["Title"] = "Review Exam";
    Layout = "~/Views/Teachers/_TeachersLayoutPage.cshtml";


    var examDetails = Model.Exam;
    int numberOfQuestionRows = Model.Questions.Count() / 4;
    if (Model.Questions.Count() % 4 > 0)
    {
        numberOfQuestionRows++;
    }
}

<h1>Exam Details For @Model.User.Name</h1>

<div>
    <hr />

    <h3>Final Grade: @Model.Grade</h3>
    <dl class="row">

        <dt class="col-sm-2">
            Title
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => examDetails.Title)
        </dd>
        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => examDetails.Description)
        </dd>
        <dt class="col-sm-2">
            Classroom
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => examDetails.Classroom.Title)
        </dd>
        <dt class="col-sm-2">
            Attended
        </dt>
        <dd class="col-sm-10">
            @if (Model.IsAttended)
            {
                <span class="badge badge-success">&#10003;</span>
            }
            else
            {
                <span class="badge badge-danger">X</span>
            }

        </dd>
    </dl>
    <div class="row text-left">
        <div class="col">
            <h4>Answers:</h4>
        </div>
    </div>

</div>
<partial name="_AnswerCards" model="@Model" />
<div>
    <a asp-action="ExamStatistics" asp-route-id="@Model.ExamID">Back to Exam Statistics</a>
</div>

ExamsProjectMvc/Views/Teachers/TeachersLogin.cshtml
@model ExamsProjectMvc.Models.LoginViewModel;
@{
    Layout = "_TeachersLayoutPage";
    ViewData["Title"] = "Login";
    ViewData["User"] = "Teacher";

}

<div class="row text-center">
    <div class="col">
        <h1>Exams Application</h1>
    </div>
</div>
<hr />
<div class="row">
    <div class="col">

            <partial name="_LoginForm" for=@Model view-data="ViewData"/>


        </div>
    </div>
</div>
@section Scripts
{
    @if (Model.IsAttempFailed)
    {
        <script>
    document.addEventListener("DOMContentLoaded", function (event) {
        alert('@(ViewData["errorMessage"] as string)');
    });
        </script>
    }
}

ExamsProjectMvc/Views/Teachers/TeachersNavbar.cshtml
@{
    string loged = Context.Request.Cookies["isLoged"];
}

<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Teachers" asp-action="Index">ExamsProjectMvc</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                @if (loged == "true")
                {
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Teachers" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Teachers" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>
</header>

ExamsProjectMvc/Views/Teachers/questionForm.cshtml
<div class="row">

    <div class="col" id="questions">

        <button onclick="addQuestion()" class="btn btn-secondary" id="addQuestionBtn" type="button">Add Another question</button>
    </div>
</div>